### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by nxnine** [pwncraft/randomcolor-generator#1]
MOAR COLORS DDD:

**Comment by pwncraft** [comment]
Hi can you please elaborate on what you would like to see? We are limited by the 16 colors of Minecraft for our choices.

**Comment by nxnine** [comment]
M O A R  C O L O R S

**Comment by pwncraft** [comment]
I will take your suggestion into consideration.

**Comment by pwncraft** [comment]
Per your request more colors have been added.
